# This file was generated by GoReleaser. DO NOT EDIT.
cask "recall" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "15a06ab088fcaab69799a707804cc607908490c59f41b5ff1be175133606b5c4"
      url "https://github.com/pratikgajjar/recall/releases/download/v#{version}/recall_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "7c163da1cb5babf3793e58bd4dcc742b84cbc8a5f4d13eb424e3fdc831be6a18"
      url "https://github.com/pratikgajjar/recall/releases/download/v#{version}/recall_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9f7dbc693aeef4087b948dd9f83186cf51ba68a22243aec31e50ebea55231670"
      url "https://github.com/pratikgajjar/recall/releases/download/v#{version}/recall_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7c561a64b66449ac16e517fea954582b59660398d5fd9d3817a6d5fd90dd10c1"
      url "https://github.com/pratikgajjar/recall/releases/download/v#{version}/recall_#{version}_linux_arm64.tar.gz"
    end
  end

  name "recall"
  desc "Search your AI chat history across Cursor, Claude Code, Codex, and pi"
  homepage "https://github.com/pratikgajjar/recall"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "recall"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/recall"]
    end
  end

  # No zap stanza required

end
