# This file was generated by GoReleaser. DO NOT EDIT.
cask "recall" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "c460d7fbeaf355cd9b1ef101c299e96b46e139e79a7ce097fee8592052eb13dd"
      url "https://github.com/pratikgajjar/recall/releases/download/v#{version}/recall_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fa4f1bec5c678c75414eb42466479b00752fc98913b0d42ae4c77ff4c87c8ceb"
      url "https://github.com/pratikgajjar/recall/releases/download/v#{version}/recall_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8b7858a56e8c976558b7799c688a412a950171142e0dc621bdee50e8519691e1"
      url "https://github.com/pratikgajjar/recall/releases/download/v#{version}/recall_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c5d0eb48be332002bb3b8176393f690cbb8b92a1bc99d97022ce9c10253f60dc"
      url "https://github.com/pratikgajjar/recall/releases/download/v#{version}/recall_#{version}_linux_arm64.tar.gz"
    end
  end

  name "recall"
  desc "Search your AI chat history across Cursor, Claude Code, Codex, and pi"
  homepage "https://github.com/pratikgajjar/recall"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "recall"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/recall"]
    end
  end

  # No zap stanza required

end
