# This file was generated by GoReleaser. DO NOT EDIT.
cask "recall" do
  version "0.4.1"

  on_macos do
    on_intel do
      sha256 "756d9e4e67a3fef7f7dfb6f4eb02f315dd7092d8c8d77a2a8d323123d7e0a68d"
      url "https://github.com/pratikgajjar/recall/releases/download/v#{version}/recall_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "63a35a2ae961b38afe51ff8a3f89a8ddd24eb9e027123852f5c58298f03476e1"
      url "https://github.com/pratikgajjar/recall/releases/download/v#{version}/recall_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9c9bebe273ced3f46ba5f7ca91978c8958798d430c37498b459c7863405c39b9"
      url "https://github.com/pratikgajjar/recall/releases/download/v#{version}/recall_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fd1381f1057b4bb42f3c641cdcd158b61be1ae910fe6c4dfd990c2749a8f0789"
      url "https://github.com/pratikgajjar/recall/releases/download/v#{version}/recall_#{version}_linux_arm64.tar.gz"
    end
  end

  name "recall"
  desc "Search your AI chat history across Cursor, Claude Code, Codex, and pi"
  homepage "https://github.com/pratikgajjar/recall"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "recall"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/recall"]
    end
  end

  # No zap stanza required

end
